### ISSUE TITLE
identity hash

### ISSUE THREAD

**Issue by HappyFakeBoulder** [HENRYMARTIN5/ULTRACODE#2]
in readme.md, ultracode claims to make python easier to use
however, its functions require an "identity hash", making it *harder* to use, even though this "identity hash" does nothing useful and is just an extra check for no reason
please remove this or make it useful

**Comment by HENRYMARTIN5** [comment]
This is a function for later on in my updates, where I will add new functions that need initiation at the start of the program. The hash is to make sure people use the uc.init() function at startup.

**Comment by HENRYMARTIN5** [comment]
I will add more functions today. Just check back in a few days and you can see the new features.

**Comment by HENRYMARTIN5** [comment]
Oh, and also, check under the **Unstable** branch. That's where I make new features.

**Comment by HappyFakeBoulder** [comment]
> where I will add new functions that need initiation at the start of the program. The hash is to make sure people use the uc.init() function at startup.

you shouldn't be adding a function and expect people to call it in all programs and verify with some constant "hash"
we can fake the hash:
```python
import uc
uc.loop(3, "print('Hip! Hip! Hooray!!!')", uc.ucHashIdentity) # no uc.init() needed!
```
and you can include initialization code directly in the module (it will run during the `import uc` statement):
```python
import sys, time, replit, newspaper # yes, this is allowed, and it's equivalent to a sequence of import lines
print("Initializing...") # or whatever your program needs to set up
replit.clear()
# your other functions go here
```

**Comment by HappyFakeBoulder** [comment]
@HENRYMARTIN5

**Comment by HENRYMARTIN5** [comment]
Oh thx

**Comment by HENRYMARTIN5** [comment]
@HappyFakeBoulder 
I am giving up and scrapping this project.
Another language is in the works!
Find the open alpha at:
https://github.com/HENRYMARTIN5/Myth/
