### ISSUE TITLE
delays and output in uc.init()

### ISSUE THREAD

**Issue by HappyFakeBoulder** [HENRYMARTIN5/ULTRACODE#3]
in the definition of ultracode's init function, it produces output that does not give meaningful information to the programmer or user and has delays between the outputs, which slows down the program and makes it a lot less practical
also, the output is colored, which looks nice but might produce strange behavior when used on terminals that don't support color

**Comment by HENRYMARTIN5** [comment]
Hmm...
I was planning on adding different versions, with or without color.
And, yes, the loading is impractical, and I will try to make it take less time.

**Comment by HappyFakeBoulder** [comment]
my point isn't for the "loading" to be *shorter*
my point is for there to be *no unnecessary delays*
why do you say "i will *try* to make it take less time"?
it's easy
just get rid of the time.sleep() statements entirely
we don't need them
